Профиль. Комментарии. Навбар
kek-flip/homework-1-spring-2024 pull request #1
Opened 2024-02-17 19:18 UTC by kek-flip

2024-02-19 21:29 UTC, wizardOfOz21 requested changes

2024-02-19 21:29 UTC, wizardOfOz21 commented on features/profile/README.md
> +  - **UX Bug** На мобилке ховер появляется при зажатии аватарки и пропадает только при клике вне аватарки. Пользователю может быть непонятно, что аватарка обновляется при нажатии на нее
Не очень понятно, что значит при зажатии аватарки, в сафари на айфоне появляется при однократном нажатии

2024-02-19 21:29 UTC, wizardOfOz21 commented on features/profile/README.md
> +  - **Bug** Возможно загрузить файл с любым расширением, отсутствует сообщение об ошибке при загрузке не изображения, ховер искажается
Если возможно загрузить любой файл, зачем тогда предыдущий баг

2024-02-19 21:29 UTC, wizardOfOz21 commented on features/profile/README.md
> +  - **Bug** При ширине экрана меньше 1300px надпись "изменить" начинает прилипать к границам кнопки. При дальнейшем уменьшении ширины надпись выходит за границы кнопки
Возможно, стоит добавить ожидаемое поведение

2024-02-19 21:29 UTC, wizardOfOz21 commented on features/profile/README.md
> +- Адрес, состоящий из латиницы считается корректным
запятая после латиницы

2024-02-19 21:29 UTC, wizardOfOz21 commented on features/profile/README.md
> +- Адрес, содержащий кириллицу в правой части считается корректным
аналогично

2024-02-19 21:29 UTC, wizardOfOz21 commented on features/profile/README.md
> +- **Bug** в левой части допускаются символы, отличные от букв, цифр и ".". Например _-+%#/@gmail.com_
с большой буквы после бага

2024-02-19 21:29 UTC, wizardOfOz21 commented on features/profile/README.md
> +- При обновлении страницы изменения телефонателефон сбрасываются
пропущен пробел

2024-02-19 21:29 UTC, wizardOfOz21 commented on features/profile/README.md
> +- **Bug** На мобилке скроллится страница при открытой модалке
Не очень понятно, опиши подробнее, а лучше со скрином

2024-02-19 21:29 UTC, wizardOfOz21 commented on features/comments/README.md
> +- Кол-во отзывов совпадает с кол-вом, указанным в шапке ресторана
Это не всегда правда

2024-02-19 21:29 UTC, wizardOfOz21 commented on features/comments/README.md
> +- **Bug** Счетчик числа отзывов после создания отзыва обновляется только при обновлении страницы или перезахода на нее
Может, добавить ссылку на описание бага с каунтером в моем отчете?

2024-02-19 21:29 UTC, wizardOfOz21 commented on features/comments/README.md
> +- **Bug** На мобилке скроллится страница при открытой модалке
Не ясно, что имеется в виду

2024-02-20 17:06 UTC, HallowAz commented on features/comments/README.md
> +- Список отзывов скроллится
наличие скроллбара, когда все отзывы умещаются - это норм?

2024-02-20 17:10 UTC, HallowAz commented on features/comments/README.md
> +- ![Длинное имя ползователя](img/long_nickname.PNG)
полЬзователя

2024-02-20 17:17 UTC, HallowAz commented on features/profile/README.md
> +- При нажатии на кнопку появляется системный интерфейс выбора файла для загрузки на сайт
Лучше уточнить что за кнопка

2024-02-20 17:21 UTC, HallowAz commented on features/profile/README.md
> +- Невозможно сохранить адрес, совпадающий с адресом другого пользователя
может стоит указать, что об этом имеется или не имеется соответствующее сообщение, как это было выше при создании отзыва?

2024-02-20 17:24 UTC, HallowAz commented on features/profile/README.md
> +- При совпадении уникальных данных (телефон, email) появляется сообщение о совпадении
Уже имеются сообщения об этом в проверках самих телефона и почты. Не считаешь, что можно оставить либо только здесь, либо только там?

2024-02-20 17:58 UTC, tomsuliana commented on features/comments/README.md
> +- **Bug** Можно оставлять несколько отзывов на ресторан с одно аккаунта
с одного аккаунта

2024-02-20 17:58 UTC, tomsuliana commented on features/navbar/README.md
> +  - **Bug** На мобилке отстается поле поиска
Остается 2 раза

2024-02-20 17:58 UTC, tomsuliana commented on features/navbar/README.md
> +### Навигация
Может в этот раздел добавить баг с тем, когда сделал заказ и попал на профиль, то потом по стрелке назад  попадаешь в пустую корзину. Возможно, это не самое лучшее поведение

2024-02-20 17:58 UTC, tomsuliana commented on features/profile/README.md
> +- У нового пользователя отображается аватарка по-умолчанию
по умолчанию без дефиса

2024-02-20 17:58 UTC, tomsuliana commented on features/profile/README.md
> +- Предлагаемые раширения загружаемых файлов _jpg, jpeg, png_
Получается что этот пункт ничего не проверяет, а просто сообщает информацию, чего быть не должно

2024-02-21 15:25 UTC, kek-flip commented on features/profile/README.md
> +  - **Bug** Возможно загрузить файл с любым расширением, отсутствует сообщение об ошибке при загрузке не изображения, ховер искажается
Отличие заключается в том, что гифка корректно отображается и воспроизводится, в отличие от файлов, не являющихся изображениями

2024-02-21 16:35 UTC, kek-flip commented on features/profile/README.md
> +- При совпадении уникальных данных (телефон, email) появляется сообщение о совпадении
Не очень понял, о чем ты

2024-02-21 16:36 UTC, kek-flip commented on features/navbar/README.md
> +  - **Bug** На мобилке отстается поле поиска
Это для двух разных страниц

2024-02-21 16:45 UTC, HallowAz commented on features/profile/README.md
> +- При совпадении уникальных данных (телефон, email) появляется сообщение о совпадении
Передумал, если суть проверки в том, что сообщение появляется, то вопрос закрыт

2024-02-21 17:28 UTC, wizardOfOz21 submitted a review, later dismissed

2024-02-21 18:31 UTC, tomsuliana commented on features/navbar/README.md
> +  - **Bug** На мобилке отстается поле поиска
Тут я имела в виду что оба раза остается, а не отстается

2024-02-21 19:06 UTC, tomsuliana commented on features/profile/README.md
> +- Предлагаемые раширения загружаемых файлов _jpg, jpeg, png_
Не исправлено и не прокомментировано

2024-02-21 19:14 UTC, HallowAz approved these changes, later dismissed

2024-02-22 06:55 UTC, tomsuliana submitted a review, later dismissed

2024-02-23 07:59 UTC, wizardOfOz21 approved these changes

2024-02-23 09:15 UTC, HallowAz approved these changes

2024-02-23 10:00 UTC, tomsuliana approved these changes

2024-02-23 13:29 UTC, merged