Registration, addresses and search done
kek-flip/homework-1-spring-2024 pull request #4
Opened 2024-02-18 21:16 UTC by tomsuliana

2024-02-19 21:57 UTC, wizardOfOz21 requested changes

2024-02-19 21:57 UTC, wizardOfOz21 commented on features/address/README.md
> +** Мобильная версия ** - _Google Chrome Version 15.5.58.28.arm64_
Нарушено md форматирование (звездочки слитно) и нет переноса строки

<img width="802" alt="image" src="https://github.com/kek-flip/homework-1-spring-2024/assets/108520625/620ef86c-4911-4e0d-807e-edbee4cdd2a1">

2024-02-19 21:57 UTC, wizardOfOz21 commented on features/registration/README.md
> +![Текст ошибки](img/error.png)
Поправить форматирование 

<img width="704" alt="image" src="https://github.com/kek-flip/homework-1-spring-2024/assets/108520625/b52fd430-10c3-47ab-b861-6533b2a23785">

2024-02-19 21:57 UTC, wizardOfOz21 commented on features/registration/README.md
> +** Мобильная версия ** - _Google Chrome Version 15.5.58.28.arm64_
Аналогично форматирование

2024-02-19 21:57 UTC, wizardOfOz21 commented on features/registration/README.md
> +![При 8 символах ошибки нет](img/8symbols.png)
Тут бы добавить баг с тем, что сообщение прижимается к инпуту

2024-02-19 21:57 UTC, wizardOfOz21 commented on features/registration/README.md
> +- Ввод частично заполненного Дня Рождения блокируется
Большие буквы "Дня Рождения"

2024-02-19 21:57 UTC, wizardOfOz21 commented on features/registration/README.md
> +- При пустых полях  имени или пароля  выдается сообщение "Неправильный логин или пароль"
Сообщение выдается при попытке войти с незаполненными полями

2024-02-19 21:57 UTC, wizardOfOz21 commented on features/search/README.md
> +** Мобильная версия ** - _Google Chrome Version 15.5.58.28.arm64_
Форматирование

2024-02-19 21:57 UTC, wizardOfOz21 commented on features/search/README.md
> +![hh](img/verstka.png)
Картинка не отображается 

<img width="178" alt="image" src="https://github.com/kek-flip/homework-1-spring-2024/assets/108520625/a6865e86-c667-4373-8803-85fce7365e15">

2024-02-19 21:57 UTC, wizardOfOz21 commented on features/search/README.md
> +- Если при поиске ничего не найдено, то выдается соотвествующее сообщение
Слишком мало про поиск написано, можно про поиск по названиям блюд, ресторанов написать и тд.

2024-02-20 18:33 UTC, HallowAz commented on features/registration/README.md
> +- При заполнении кириллицей появляется соотвествующая ошибка
В целом можно к багу отнести, потому что домен почты бывает написан кириллицей

2024-02-20 18:37 UTC, HallowAz commented on features/registration/README.md
> +- **Bug** При попытке ввода дня больше 100 лет назад выдается ошибка, хотя есть люди старше 100 лет и они, должно быть, больше всех нуждаются в доставке еды
Дополнение милое и смешное, но просили писать сухо и только по факту

2024-02-20 18:41 UTC, HallowAz commented on features/registration/README.md
> +
Может добавить пару слов про то, как ведёт себя модалка, при нажатии мимо или на её кнопки? Не вижу обзора кнопок "Далее", "Уже есть аккаунт", крестика

2024-02-20 18:42 UTC, HallowAz commented on features/search/README.md
> +**Мобильная версия** - _Google Chrome Version 15.5.58.28.arm64_
Можно добавить пункты о верстке, корректно ли она работает

2024-02-21 08:07 UTC, kek-flip requested changes

2024-02-21 08:07 UTC, kek-flip commented on features/registration/README.md
> +- При заполнении кириллицей появляется соотвествующая ошибка
Согласен

2024-02-21 08:07 UTC, kek-flip commented on features/registration/README.md
> +- **Bug** При попытке ввода дня больше 100 лет назад выдается ошибка, хотя есть люди старше 100 лет и они, должно быть, больше всех нуждаются в доставке еды
Я бы не относил это к багу вовсе

2024-02-21 08:07 UTC, kek-flip commented on features/registration/README.md
> +![Фото после замены почты на новую](img/zamenauser.png)
Тут, видимо, вместо почты должно быть имя пользователя

2024-02-21 08:07 UTC, kek-flip commented on features/registration/README.md
> +- **Bug** Текст ошибок прижимается к инпуту
Я бы не считал это багом, так как ошибки специально прижимаются к инпуту, чтобы пользователю было понятно в каком поле ошибка

2024-02-21 08:07 UTC, kek-flip commented on features/registration/README.md
> +- При попытке заполнения очень длинного пароля поле пароля не увеличивается в размере
Не очень понял этот пункт
Можешь, пожалуйста, в ответе расписать подробнее?

2024-02-21 08:07 UTC, kek-flip commented on features/registration/README.md
> +- Ввод частично заполненного дня рождения блокируется
Что значит частично заполненный?

2024-02-21 08:07 UTC, kek-flip commented on features/registration/README.md
> +- При вводе валидного телефона регистрация проходит успешно
Что считается валидным номером телефона?
UDP. Вспомнил, что у нас на уровне маски номер начинается с +79. Мне кажется, стоит указать эту особенность

2024-02-21 08:07 UTC, kek-flip commented on features/registration/README.md
> +- При наличии в базе введенного номера телефона выдается ошибка о том, что такой номер уже существует
Присутствует ли ошибка с неисчезающим сообщением об ошибке, как при вводе почты и номера телефона?

2024-02-21 18:04 UTC, tomsuliana commented on features/registration/README.md
> +- **Bug** При попытке ввода дня больше 100 лет назад выдается ошибка, хотя есть люди старше 100 лет и они, должно быть, больше всех нуждаются в доставке еды
Может все-таки отнести?

2024-02-21 18:05 UTC, tomsuliana commented on features/registration/README.md
> +- **Bug** Текст ошибок прижимается к инпуту
Данный баг я добавила, исходя из комментариев Гамида. Можете между собой как-то решить, является ли это багом.

2024-02-21 18:08 UTC, tomsuliana commented on features/registration/README.md
> +- При попытке заполнения очень длинного пароля поле пароля не увеличивается в размере
Когда-то вроде у вас был такой баг, что если ввести в инпут много символов, то в какой-то момент он начинает расти вместе с модалкой, чтобы весь текст был виден. Теперь же весь текст прокручивается и видны только последние символы.

2024-02-21 18:08 UTC, tomsuliana commented on features/registration/README.md
> +- Ввод частично заполненного дня рождения блокируется
Например, если с компа ввести день и месяц, а год не вводить

2024-02-21 18:13 UTC, tomsuliana commented on features/registration/README.md
> +- При наличии в базе введенного номера телефона выдается ошибка о том, что такой номер уже существует
Реально, не будет

2024-02-21 19:15 UTC, tomsuliana commented on features/address/README.md
> +** Мобильная версия ** - _Google Chrome Version 15.5.58.28.arm64_
исправила

2024-02-21 19:15 UTC, tomsuliana commented on features/registration/README.md
> +![Текст ошибки](img/error.png)
исправила

2024-02-21 19:16 UTC, tomsuliana commented on features/registration/README.md
> +![При 8 символах ошибки нет](img/8symbols.png)
Решите этот вопрос с Максимом

2024-02-21 19:16 UTC, tomsuliana commented on features/registration/README.md
> +- Ввод частично заполненного Дня Рождения блокируется
исправила

2024-02-21 19:16 UTC, tomsuliana commented on features/registration/README.md
> +- При пустых полях  имени или пароля  выдается сообщение "Неправильный логин или пароль"
исправила

2024-02-21 19:16 UTC, tomsuliana commented on features/search/README.md
> +** Мобильная версия ** - _Google Chrome Version 15.5.58.28.arm64_
исправила

2024-02-21 19:16 UTC, tomsuliana commented on features/search/README.md
> +![hh](img/verstka.png)
исправила

2024-02-21 19:17 UTC, tomsuliana commented on features/search/README.md
> +- Если при поиске ничего не найдено, то выдается соотвествующее сообщение
исправила

2024-02-21 19:17 UTC, tomsuliana commented on features/registration/README.md
> +- При заполнении кириллицей появляется соотвествующая ошибка
отнесла к багу

2024-02-21 19:17 UTC, tomsuliana commented on features/registration/README.md
> +
Добавила

2024-02-21 19:17 UTC, tomsuliana commented on features/search/README.md
> +**Мобильная версия** - _Google Chrome Version 15.5.58.28.arm64_
Добавила

2024-02-21 19:18 UTC, tomsuliana commented on features/registration/README.md
> +![Фото после замены почты на новую](img/zamenauser.png)
исправила

2024-02-21 19:18 UTC, tomsuliana commented on features/registration/README.md
> +- При вводе валидного телефона регистрация проходит успешно
указала

2024-02-21 19:18 UTC, tomsuliana commented on features/registration/README.md
> +- При наличии в базе введенного номера телефона выдается ошибка о том, что такой номер уже существует
исправила

2024-02-21 19:31 UTC, HallowAz commented on features/registration/README.md
> +- **Bug** При попытке ввода дня больше 100 лет назад выдается ошибка, хотя есть люди старше 100 лет и они, должно быть, больше всех нуждаются в доставке еды
я считаю багом всё равно

2024-02-21 19:32 UTC, HallowAz submitted a review, later dismissed

2024-02-22 05:41 UTC, wizardOfOz21 submitted a review, later dismissed

2024-02-22 05:47 UTC, kek-flip approved these changes, later dismissed

2024-02-22 10:37 UTC, kek-flip approved these changes

2024-02-22 12:16 UTC, HallowAz approved these changes

2024-02-22 12:32 UTC, wizardOfOz21 approved these changes

2024-02-22 12:33 UTC, merged