create tests for creating order, promocodes and order status
kek-flip/homework-1-spring-2024 pull request #5
Opened 2024-02-20 16:38 UTC by HallowAz

2024-02-20 18:14 UTC, wizardOfOz21 requested changes

2024-02-20 18:14 UTC, wizardOfOz21 commented on features/CreateOrder/README.md
> +**Десктоп бразуер** - _Google Chrome 121.0.6167.185_
опечатка - бразуер

2024-02-20 18:14 UTC, wizardOfOz21 commented on features/CreateOrder/README.md
> +- Нельзя оформить с адресом и способом оплаты - картой онлайн, но с незаполненным полем номера карты
Думаю, можно просто написать, что нельзя оформить без заполнения всех полей

2024-02-20 18:14 UTC, wizardOfOz21 commented on features/CreateOrder/README.md
> +![Потеря цены доставки при обновлении](img/lost_delivery_price.png)
Скриншот тут в принципе ничего не иллюстрирует, можно либо вообще убрать, либо вставить видео с обновлением страницы, где видно обнуление

2024-02-20 18:14 UTC, wizardOfOz21 commented on features/CreateOrder/README.md
> +![Верстка полетела](img/verstka_lost.png)
Сделай скрин поменьше размером (вставляешь через html тег img и указываешь ширину атрибутом) и добавь отступ снизу 

<img width="641" alt="image" src="https://github.com/kek-flip/homework-1-spring-2024/assets/108520625/02dc2343-354b-4eb0-8b4b-82e626b1fa1d">

2024-02-20 18:14 UTC, wizardOfOz21 commented on features/CreateOrder/README.md
> +- **Bug** Верстка названий товаров и кнопки подтверждения промокода неправильно работает при уменьшении окна по горизонтали
корзина описана в моем отчете по корзине, а кнопка промокодов - в баге ниже, этот баг можно убрать

2024-02-20 18:14 UTC, wizardOfOz21 commented on features/CreateOrder/README.md
> +- **Bug** Верстка названий кнопки подтверждения промокода неправильно работает при уменьшении окна по горизонтали
- названия кнопки*
- уменьшение по горизонтали = уменьшение ширины, так более понятно

2024-02-20 18:14 UTC, wizardOfOz21 commented on features/CreateOrder/README.md
> +- **Bug** Верстка названий цен и кнопки подтверждения промокода неправильно работает при уменьшении окна по горизонтали
Опять же про корзину, можно убрать и скрин заменить только на скрин правой части страницы

2024-02-20 18:14 UTC, wizardOfOz21 commented on features/Promocodes/README.md
> +**Десктоп бразуер** - _Google Chrome 121.0.6167.185_
бразуер

2024-02-20 18:14 UTC, wizardOfOz21 commented on features/Promocodes/README.md
> +![Невозможность применить промокод](img/the_worst_bug.png)
Не понял, к чему этот скрин. Либо видео, либо без скрина

2024-02-20 18:14 UTC, wizardOfOz21 commented on features/Promocodes/README.md
> +- **Bug** При заходе в другой профиль с того же браузера, остаются заполненными поля и применены промокоды предыдущего пользователя, причём отменить его нельзя, при этом цена считается не учитывая ег
Запятая перед "не учитывая его"

2024-02-20 18:14 UTC, wizardOfOz21 commented on features/Promocodes/README.md
> +- Промокод "SHYSH30" нельзя использовать больше одного раза
Предлагаю не делать отдельные разделы про каждый промокод. Тут баги применимы ко всем промокодам, как я понимаю, - выносим их в пункты списка без указания названия промокода. Назначение и применимость промокодов можно описать тоже в общем списке

2024-02-20 18:14 UTC, wizardOfOz21 commented on features/Promocodes/README.md
> +- **Bug** Промокоды нельзя комбинировать
Не уверен, что это баг. Даже если такое задумывалось, у нас нет интерфейса для этого, то есть это скорее нереализованный функционал, можно убрать этот пункт

2024-02-20 18:14 UTC, wizardOfOz21 commented on features/Promocodes/README.md
> +## Вёрстка
Давай с буквой е, как раньше

2024-02-20 18:14 UTC, wizardOfOz21 commented on features/Promocodes/README.md
> +- Мобильный адаптив поддерживается
Можно описать, как изменяется вид страницы в мобилке по пунктам

2024-02-20 18:14 UTC, wizardOfOz21 commented on features/Promocodes/README.md
> +![Промокод верстка](img/promo_verstka.png)
Уменьши скриншот

2024-02-20 18:14 UTC, wizardOfOz21 commented on features/StatatusOrder/README.md
> +**Десктоп бразуер** - _Google Chrome 121.0.6167.185_
бразуер

2024-02-20 18:14 UTC, wizardOfOz21 commented on features/StatatusOrder/README.md
> +- У заказов меняется статус в зависимости от стадии доставки
Скриншоты к положительным кейсам тоже желательно добавлять (у себя в отчетах тоже добавлю)

2024-02-20 18:14 UTC, wizardOfOz21 commented on features/StatatusOrder/README.md
> +- **Bug** статус заказа меняется только при обновлении страницы
После бага с большой буквы

2024-02-20 18:14 UTC, wizardOfOz21 commented on features/StatatusOrder/README.md
> +- **Bug** длительность времени доставки заказа всегда одинаково и не меняется в зависимости от времени, указанном в главном меню. Всегда 30 мин
- с большой буквы
- предложение не согласованно

2024-02-20 18:14 UTC, wizardOfOz21 commented on features/StatatusOrder/README.md
> +- При множестве товаров, скроллятся корректно
* Если товаров много, список скролится

2024-02-20 18:14 UTC, wizardOfOz21 commented on features/StatatusOrder/README.md
> +- **Bug** скроллбар имеется независимо от того, есть ли в нём необходимость (если кол-во товаров недостаточно)
С большой буквы

2024-02-20 18:14 UTC, wizardOfOz21 commented on features/StatatusOrder/README.md
> +![Ненужный скроллбар](img/status_order.png)
Уменьшить скриншот

2024-02-20 18:14 UTC, wizardOfOz21 commented on features/StatatusOrder/README.md
> +## Вёрстка
Давай с е

2024-02-20 18:14 UTC, wizardOfOz21 commented on features/StatatusOrder/README.md
> +- **Bug** При изменении длины в мобильной версии статус заказа заходит на номер заказа
при изменении ширины*

2024-02-20 18:14 UTC, wizardOfOz21 commented on features/StatatusOrder/README.md
> +![Статус вёрстка](img/status_verstka.png)
- Такая ширина для мобилки не очень правдоподобная, нормально выглядеть должно примерно до 300px ширины, лучше сделать скрин с шириной побольше
- Уменьшить скриншот в разметке

2024-02-20 18:14 UTC, wizardOfOz21 commented on features/StatatusOrder/README.md
> +- Мобильный адаптив поддерживается
Описать, как поддерживается

2024-02-20 18:14 UTC, wizardOfOz21 commented on features/StatatusOrder/README.md
> +- **Bug** При изменении длины в страница статуса заказа количество товара заходит на название товара
при изменении ширины страницы*

2024-02-20 18:14 UTC, wizardOfOz21 commented on features/StatatusOrder/README.md
> +![Статус страница вёрстка](img/str_status_verstka.png)
уменьшить скриншот

2024-02-20 19:10 UTC, tomsuliana commented on features/CreateOrder/README.md
> +- Кнопка "Оформить заказ" работает корректно
"работает корректно" - это что-то вроде антипаттерна. Лучше мб либо вообще не писать, либо написать что будет происходит (оформление заказа, переход на профиль и тд)

2024-02-20 19:10 UTC, tomsuliana commented on features/Promocodes/README.md
> +- **Bug** При повтороном оформлении заказа, действие старого промокода "PRINESYFREE" сохраняется
1. повторном 
2. запятая не нужна

2024-02-20 19:10 UTC, tomsuliana commented on features/Promocodes/README.md
> +- **Bug** При повтороном оформлении заказа, действие старого промокода "SHYSH30" сохраняется
аналогично

2024-02-20 19:10 UTC, tomsuliana commented on features/Promocodes/README.md
> +- **Bug** Применение промокода не влияет на итогову цену заказа после оформления
итоговую

2024-02-20 19:10 UTC, tomsuliana commented on features/Promocodes/README.md
> +- Промокоды корректно меняют сумму заказа на странице заказа
тут тоже можно написать, что они меняют цену согласно цифре в промокоде

2024-02-20 19:10 UTC, tomsuliana commented on features/Promocodes/README.md
> +- **Bug** на телефоне при истёкшом промокоде предупреждение заезжает на лейбл
истекшем

2024-02-20 19:10 UTC, tomsuliana commented on features/StatatusOrder/README.md
> +- При отсутсвии заказов имеется корректное сообщение
отсутствии

2024-02-20 19:17 UTC, HallowAz commented on features/CreateOrder/README.md
> +**Десктоп бразуер** - _Google Chrome 121.0.6167.185_
Исправил

2024-02-20 19:25 UTC, HallowAz commented on features/CreateOrder/README.md
> +- Нельзя оформить с адресом и способом оплаты - картой онлайн, но с незаполненным полем номера карты
Поменял, тоже так думаю

2024-02-20 19:35 UTC, HallowAz commented on features/CreateOrder/README.md
> +![Потеря цены доставки при обновлении](img/lost_delivery_price.png)
то, что в принципе сумма доставки равна нулю - это ненормально. Жду ещё коммента

2024-02-20 20:16 UTC, HallowAz commented on features/CreateOrder/README.md
> +![Верстка полетела](img/verstka_lost.png)
Сделал

2024-02-20 20:29 UTC, HallowAz commented on features/CreateOrder/README.md
> +- **Bug** Верстка названий товаров и кнопки подтверждения промокода неправильно работает при уменьшении окна по горизонтали
Убрал

2024-02-20 20:32 UTC, HallowAz commented on features/CreateOrder/README.md
> +- **Bug** Верстка названий кнопки подтверждения промокода неправильно работает при уменьшении окна по горизонтали
Поменял

2024-02-20 20:45 UTC, HallowAz commented on features/CreateOrder/README.md
> +- **Bug** Верстка названий цен и кнопки подтверждения промокода неправильно работает при уменьшении окна по горизонтали
Поменял

2024-02-20 20:45 UTC, HallowAz commented on features/Promocodes/README.md
> +**Десктоп бразуер** - _Google Chrome 121.0.6167.185_
Поменял

2024-02-20 20:55 UTC, HallowAz commented on features/Promocodes/README.md
> +![Невозможность применить промокод](img/the_worst_bug.png)
Достаточно полно описал, убрал скрин

2024-02-20 20:56 UTC, HallowAz commented on features/Promocodes/README.md
> +- **Bug** При заходе в другой профиль с того же браузера, остаются заполненными поля и применены промокоды предыдущего пользователя, причём отменить его нельзя, при этом цена считается не учитывая ег
добавил

2024-02-20 21:00 UTC, HallowAz commented on features/Promocodes/README.md
> +- Промокод "SHYSH30" нельзя использовать больше одного раза
на принесифри правила некоторые не распространяются. Но в целом понял тебя, поменял структуру, как посчитал правильным

2024-02-20 21:01 UTC, HallowAz commented on features/Promocodes/README.md
> +- **Bug** Промокоды нельзя комбинировать
убрал

2024-02-20 21:04 UTC, HallowAz commented on features/Promocodes/README.md
> +## Вёрстка
сделал

2024-02-20 21:22 UTC, HallowAz commented on features/Promocodes/README.md
> +- Мобильный адаптив поддерживается
Описал

2024-02-20 21:28 UTC, HallowAz commented on features/Promocodes/README.md
> +![Промокод верстка](img/promo_verstka.png)
уменьшил

2024-02-20 21:28 UTC, HallowAz commented on features/StatatusOrder/README.md
> +**Десктоп бразуер** - _Google Chrome 121.0.6167.185_
исправил

2024-02-20 21:30 UTC, HallowAz commented on features/StatatusOrder/README.md
> +- У заказов меняется статус в зависимости от стадии доставки
Добавил

2024-02-20 21:35 UTC, HallowAz commented on features/StatatusOrder/README.md
> +- **Bug** статус заказа меняется только при обновлении страницы
Сделал

2024-02-20 21:36 UTC, HallowAz commented on features/StatatusOrder/README.md
> +- **Bug** длительность времени доставки заказа всегда одинаково и не меняется в зависимости от времени, указанном в главном меню. Всегда 30 мин
Вроде исправил, проверь ещё раз

2024-02-20 21:36 UTC, HallowAz commented on features/StatatusOrder/README.md
> +- При множестве товаров, скроллятся корректно
Поменял

2024-02-20 21:36 UTC, HallowAz commented on features/StatatusOrder/README.md
> +- **Bug** скроллбар имеется независимо от того, есть ли в нём необходимость (если кол-во товаров недостаточно)
сделал

2024-02-20 21:38 UTC, HallowAz commented on features/StatatusOrder/README.md
> +![Ненужный скроллбар](img/status_order.png)
уменьшил

2024-02-20 21:39 UTC, HallowAz commented on features/StatatusOrder/README.md
> +## Вёрстка
е

2024-02-20 21:39 UTC, HallowAz commented on features/StatatusOrder/README.md
> +- **Bug** При изменении длины в мобильной версии статус заказа заходит на номер заказа
поменял

2024-02-20 21:40 UTC, HallowAz commented on features/StatatusOrder/README.md
> +![Статус вёрстка](img/status_verstka.png)
Тогда проблемы нет. убрал

2024-02-20 21:44 UTC, HallowAz commented on features/StatatusOrder/README.md
> +- Мобильный адаптив поддерживается
описал

2024-02-20 21:45 UTC, HallowAz commented on features/StatatusOrder/README.md
> +- **Bug** При изменении длины в страница статуса заказа количество товара заходит на название товара
поменял

2024-02-20 21:45 UTC, HallowAz commented on features/StatatusOrder/README.md
> +![Статус страница вёрстка](img/str_status_verstka.png)
уменьшил

2024-02-20 21:46 UTC, HallowAz commented on features/CreateOrder/README.md
> +- Кнопка "Оформить заказ" работает корректно
поменял

2024-02-20 21:46 UTC, HallowAz commented on features/Promocodes/README.md
> +- **Bug** При повтороном оформлении заказа, действие старого промокода "PRINESYFREE" сохраняется
исправил

2024-02-20 21:47 UTC, HallowAz commented on features/Promocodes/README.md
> +- **Bug** При повтороном оформлении заказа, действие старого промокода "SHYSH30" сохраняется
не актуально

2024-02-20 21:47 UTC, HallowAz commented on features/Promocodes/README.md
> +- **Bug** Применение промокода не влияет на итогову цену заказа после оформления
поменял

2024-02-20 21:48 UTC, HallowAz commented on features/Promocodes/README.md
> +- Промокоды корректно меняют сумму заказа на странице заказа
добавил

2024-02-20 21:48 UTC, HallowAz commented on features/Promocodes/README.md
> +- **Bug** на телефоне при истёкшом промокоде предупреждение заезжает на лейбл
сделал

2024-02-20 21:48 UTC, HallowAz commented on features/StatatusOrder/README.md
> +- При отсутсвии заказов имеется корректное сообщение
сделал

2024-02-21 07:43 UTC, kek-flip commented on features/CreateOrder/README.md
> +- Кнопка "Оформить заказ" редиректит на страницу профиля с историей заказов
Редирект происходит только при успешном оформлении заказа, это надо уточнить

2024-02-21 07:43 UTC, kek-flip commented on features/CreateOrder/README.md
> +- Нельзя оформить без заполнения хотя бы одного поля
Нужно переформулировать, так как сейчас говориться, что нужно заполнить хотя бы одно поле, чтобы сделать заказ, а по факту нужно заполнить все поля

2024-02-21 07:43 UTC, kek-flip commented on features/StatatusOrder/README.md
> +- При отсутствии заказов имеется корректное сообщение
Какое?

2024-02-21 08:04 UTC, wizardOfOz21 commented on features/CreateOrder/README.md
> +![Потеря цены доставки при обновлении](img/lost_delivery_price.png)
Не нормально, но описано именно обнуление при обновление, то динамический процесс, поэтому скриншот не стыкуется с описанием как-то

2024-02-21 08:08 UTC, kek-flip requested changes
(я случайно запросил повторный ревью сам у себя)

2024-02-21 08:38 UTC, HallowAz commented on features/CreateOrder/README.md
> +![Потеря цены доставки при обновлении](img/lost_delivery_price.png)
хорошо, оставлю описание, а для скрина плюс баг накину

2024-02-21 08:41 UTC, HallowAz commented on features/CreateOrder/README.md
> +- Кнопка "Оформить заказ" редиректит на страницу профиля с историей заказов
добавил

2024-02-21 08:42 UTC, HallowAz commented on features/CreateOrder/README.md
> +- Нельзя оформить без заполнения хотя бы одного поля
Сделал

2024-02-21 08:47 UTC, HallowAz commented on features/StatatusOrder/README.md
> +- При отсутствии заказов имеется корректное сообщение
добавил

2024-02-21 09:03 UTC, wizardOfOz21 requested changes

2024-02-21 09:03 UTC, wizardOfOz21 commented on features/StatatusOrder/README.md
> +    <img src="img/orders.png" width=300>
Добавь отступы к скриншоту 

<img width="835" alt="image" src="https://github.com/kek-flip/homework-1-spring-2024/assets/108520625/9d0fc497-28d0-4fb2-9977-0419ada8c7b6">

2024-02-21 09:03 UTC, wizardOfOz21 commented on features/StatatusOrder/README.md
> +- **Bug** Длительность времени доставки заказа всегда одинакова и не меняется в зависимости от времени, указанном в главном меню. Всегда 30 мин
указанного*

2024-02-21 16:20 UTC, HallowAz commented on features/StatatusOrder/README.md
> +    <img src="img/orders.png" width=300>
исправил

2024-02-21 16:21 UTC, HallowAz commented on features/StatatusOrder/README.md
> +- **Bug** Длительность времени доставки заказа всегда одинакова и не меняется в зависимости от времени, указанном в главном меню. Всегда 30 мин
сделал

2024-02-21 16:46 UTC, kek-flip approved these changes, later dismissed

2024-02-21 17:24 UTC, wizardOfOz21 approved these changes, later dismissed

2024-02-21 19:14 UTC, tomsuliana commented on features/Promocodes/README.md
> +- Промокоды корректно меняют сумму заказа на странице заказа
указанной

2024-02-22 06:53 UTC, tomsuliana submitted a review, later dismissed

2024-02-22 06:53 UTC, tomsuliana commented on features/Promocodes/README.md
> +- Промокоды корректно меняют сумму заказа на странице, согласно цифре, укзанной в промокоде
указанной

2024-02-22 12:45 UTC, tomsuliana approved these changes

2024-02-22 12:47 UTC, wizardOfOz21 approved these changes

2024-02-22 13:18 UTC, kek-flip approved these changes

2024-02-22 13:20 UTC, merged